name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v3.1.0
        with:
          aqua_version: v2.42.2
      - run: container-structure-test version
      - run: container-structure-test test -c container-structure-test.yaml --image debian:slim
